# Resin instance particulars

server:
    host: "localhost"
    port: 9999
    username: "monitorRole"
    password: "admin"

# Resin MBeans
mbeans:
    domainName: "resin"
    types: [CacheStore,ClusterServer,ConnectionPool,Memory,Server,ThreadPool,TransactionManager,WebApp]
    # Uses regular expressions to match the pattern
    excludePatterns: [.*ClusterIndex$]
        

#prefix used to show up metrics in AppDynamics
metricPrefix:  "Custom Metrics|Resin|"

